In [2]:
import requests
import json
from pprint import pprint
import csv
import pandas as pd
from sodapy import Socrata
app_token = "Um1VWzrf55cHNeIqtlqqKHux9"

In [3]:
#url = "https://data.ny.gov/resource/cm56-widp.json"
file_csv = "Motor_Vehicle_Crashes_-_Vehicle_Information__Three_Year_Window.csv"
#response = requests.get(url)

In [4]:
#data = response.json()
#pprint(data)

In [5]:
#print(len(data))

In [6]:
data_pd = pd.read_csv(file_csv)
data_pd.head()

,Year,Case Vehicle ID,Vehicle Body Type,Registration Class,Action Prior to Accident,Type / Axles of Truck or Bus,Direction of Travel,Fuel Type,Vehicle Year,State of Registration,Number of Occupants,Engine Cylinders,Vehicle Make,Contributing Factor 1,Contributing Factor 1 Description,Contributing Factor 2,Contributing Factor 2 Description,Event Type,Partial VIN
0,2016,13364291,SUBURBAN,PASSENGER OR SUBURBAN,Changing Lanes,Not Entered,West,Gas,2012.0,NY,1.0,4.0,MINI,HUMAN,Unsafe Lane Changing,HUMAN,Not Applicable,Not Applicable,WMWZC3C57CWL81108
1,2016,13364304,PICKUP TRUCK,PASSENGER OR SUBURBAN,Going Straight Ahead,Not Entered,East,Gas,2014.0,NY,2.0,6.0,CHEVR,ENVMT,Pavement Slippery,HUMAN,Not Applicable,Not Applicable,3GCUKREH8EG196335
2,2016,13364305,4 DOOR SEDAN,PASSENGER OR SUBURBAN,Going Straight Ahead,Not Entered,North,Gas,2007.0,NY,1.0,4.0,HONDA,ENVMT,Pavement Slippery,HUMAN,Not Applicable,Not Applicable,1HGCM56387A220086
3,2016,13364307,SUBURBAN,PASSENGER OR SUBURBAN,Going Straight Ahead,Not Entered,North,Gas,2011.0,NY,4.0,4.0,CHEVR,ENVMT,Pavement Slippery,ENVMT,Obstruction/ Debris,Unknown,2CNFLCEC1B6362978
4,2016,13364306,SUBURBAN,PASSENGER OR SUBURBAN,Going Straight Ahead,Not Entered,North,Gas,2004.0,NY,1.0,6.0,BUICK,ENVMT,Pavement Slippery,HUMAN,Not Applicable,"Snow Embankment, Collision With Fixed Object",3G5DA03E04S597761

In [7]:
len(data_pd)

1654482

In [8]:
client = Socrata("data.ny.gov", app_token)
results = client.get("cm56-widp", limit=2000000)
results_df = pd.DataFrame.from_records(results)
results_df.head()

,action_prior_to_accident,case_vehicle_id,contributing_factor_1,contributing_factor_1_description,contributing_factor_2,contributing_factor_2_description,direction_of_travel,engine_cylinders,event_type,fuel_type,number_of_occupants,partial_vin,registration_class,state_of_registration,type_axles_of_truck_or_bus,vehicle_body_type,vehicle_make,vehicle_year,year
0,Unknown,12100031,HUMAN,Not Entered,HUMAN,Not Entered,Unknown,NaN,Not Entered,Not Entered,NaN,NaN,Not Entered,NaN,Not Entered,UNKNOWN VEHICLE,NaN,NaN,2014
1,Slowing or Stopping,12638921,HUMAN,Unknown,HUMAN,Not Entered,South,NaN,Not Entered,Not Entered,2,NaN,Not Entered,NJ,Not Entered,TAXI,NaN,NaN,2014
2,Unknown,12011955,HUMAN,Not Entered,HUMAN,Not Entered,Unknown,NaN,Not Entered,Not Entered,NaN,NaN,Not Entered,NaN,Not Entered,UNKNOWN VEHICLE,NaN,NaN,2014
3,Unknown,12563354,HUMAN,Unknown,HUMAN,Not Entered,North,NaN,Not Entered,Not Entered,NaN,NaN,Not Entered,NaN,Not Entered,UNKNOWN VEHICLE,NaN,NaN,2014
4,Backing,12574060,HUMAN,Not Entered,HUMAN,Not Entered,Unknown,NaN,Not Entered,Not Entered,1,NaN,Not Entered,NY,Not Entered,SUBURBAN,NaN,NaN,2014

In [9]:
len(results_df)

1654482

In [10]:
#print(results_df["year"].unique())

In [11]:
results_df.to_csv("data_via_api_key.csv")
results_clean_df = results_df

In [12]:
del results_clean_df["case_vehicle_id"]
results_clean_df.head()

,action_prior_to_accident,contributing_factor_1,contributing_factor_1_description,contributing_factor_2,contributing_factor_2_description,direction_of_travel,engine_cylinders,event_type,fuel_type,number_of_occupants,partial_vin,registration_class,state_of_registration,type_axles_of_truck_or_bus,vehicle_body_type,vehicle_make,vehicle_year,year
0,Unknown,HUMAN,Not Entered,HUMAN,Not Entered,Unknown,NaN,Not Entered,Not Entered,NaN,NaN,Not Entered,NaN,Not Entered,UNKNOWN VEHICLE,NaN,NaN,2014
1,Slowing or Stopping,HUMAN,Unknown,HUMAN,Not Entered,South,NaN,Not Entered,Not Entered,2,NaN,Not Entered,NJ,Not Entered,TAXI,NaN,NaN,2014
2,Unknown,HUMAN,Not Entered,HUMAN,Not Entered,Unknown,NaN,Not Entered,Not Entered,NaN,NaN,Not Entered,NaN,Not Entered,UNKNOWN VEHICLE,NaN,NaN,2014
3,Unknown,HUMAN,Unknown,HUMAN,Not Entered,North,NaN,Not Entered,Not Entered,NaN,NaN,Not Entered,NaN,Not Entered,UNKNOWN VEHICLE,NaN,NaN,2014
4,Backing,HUMAN,Not Entered,HUMAN,Not Entered,Unknown,NaN,Not Entered,Not Entered,1,NaN,Not Entered,NY,Not Entered,SUBURBAN,NaN,NaN,2014

In [13]:
del results_clean_df["partial_vin"]
results_clean_df.head()

,action_prior_to_accident,contributing_factor_1,contributing_factor_1_description,contributing_factor_2,contributing_factor_2_description,direction_of_travel,engine_cylinders,event_type,fuel_type,number_of_occupants,registration_class,state_of_registration,type_axles_of_truck_or_bus,vehicle_body_type,vehicle_make,vehicle_year,year
0,Unknown,HUMAN,Not Entered,HUMAN,Not Entered,Unknown,NaN,Not Entered,Not Entered,NaN,Not Entered,NaN,Not Entered,UNKNOWN VEHICLE,NaN,NaN,2014
1,Slowing or Stopping,HUMAN,Unknown,HUMAN,Not Entered,South,NaN,Not Entered,Not Entered,2,Not Entered,NJ,Not Entered,TAXI,NaN,NaN,2014
2,Unknown,HUMAN,Not Entered,HUMAN,Not Entered,Unknown,NaN,Not Entered,Not Entered,NaN,Not Entered,NaN,Not Entered,UNKNOWN VEHICLE,NaN,NaN,2014
3,Unknown,HUMAN,Unknown,HUMAN,Not Entered,North,NaN,Not Entered,Not Entered,NaN,Not Entered,NaN,Not Entered,UNKNOWN VEHICLE,NaN,NaN,2014
4,Backing,HUMAN,Not Entered,HUMAN,Not Entered,Unknown,NaN,Not Entered,Not Entered,1,Not Entered,NY,Not Entered,SUBURBAN,NaN,NaN,2014

In [14]:
results_clean_df.to_csv("data_via_api_key_cleansing1.csv")

In [28]:
len(results_clean_df)

1654482

In [39]:
# cleaning results_clean_df using notes from last session
results_clean_df1 = results_clean_df.loc[(results_clean_df.contributing_factor_1.notnull()) & (results_clean_df.contributing_factor_2.notnull()), :]
results_clean_df1 = results_clean_df1.loc[(results_clean_df1["action_prior_to_accident"] != "Unknown") &
                                         (results_clean_df1["contributing_factor_1_description"] != "Unknown") &
                                         (results_clean_df1["contributing_factor_2_description"] != "Unknown") &
                                         (results_clean_df1["event_type"] != "Unknown") &
                                         (results_clean_df1["vehicle_body_type"] != "UNKNOWN VEHICLE"),:]
#results_clean_df1 = results_clean_df1.loc[(results_clean_df1["action_prior_to_accident"] != "Not Applicable") &
#                                           (results_clean_df1["contributing_factor_1_description"] != "Not Applicable") &
#                                          (results_clean_df1["contributing_factor_1_description"] != "Not Entered") &
#                                          (results_clean_df1["contributing_factor_2_description"] != "Not Applicable") &
#                                          (results_clean_df1["contributing_factor_2_description"] != "Not Entered") &
#                                          (results_clean_df1["event_type"] != "Not Applicable") &
#                                          (results_clean_df1["event_type"] != "Not Entered") &
#                                          (results_clean_df1["fuel_type"] != "Not Entered") &
#                                          (results_clean_df1["fuel_type"] != "Unknown") &
#                                          (results_clean_df1["vehicle_body_type"] != "Not Entered"), :]

len(results_clean_df1)

# 1393310
#temp_df = results_clean_df.loc[(results_clean_df.contributing_factor_1 != "HUMAN") & 
#                               (results_clean_df.contributing_factor_1 != "VEHICLE") &
#                              (results_clean_df.contributing_factor_1 != "ENVMT"),:]
#temp_df.head()

1393310

In [40]:
results_clean_df1.to_csv("results_clean_df1.csv")